version: '3'

services:
  db2:
    container_name: mysql_toc2
    image: mysql:5.7-oracle
    environment:
      MYSQL_DATABASE: db_videogames
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "9905:3306"
  db:
    container_name: mysql_toc
    image: mysql:5.7-oracle
    environment:
      MYSQL_DATABASE: db_videogames
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "9904:3306"
    depends_on:
      - db2

# docker-compose -f php_mysql/compose.yml up

# docker-php-ext-install mysqli
# docker-php-ext-enable mysqli

#https://stackoverflow.com/questions/5210309/how-can-i-enable-the-federated-engine-in-mysql-after-installation